services:
  2fmusic:
    image: ghcr.io/yuexps/2fmusic:latest
    container_name: 2fmusic
    ports:
      - "23237:23237"
    volumes:
      - ./:/app/data
      - /vol2/1000/Music:/vol2/1000/Music # 挂载本地音乐文件夹（自行修改）
    environment:
      - FLASK_ENV=production
      - TZ=Asia/Shanghai
      - PORT=23237
      - APP_PASSWORD=
    restart: unless-stopped