services:
  2fmusic:
    image: ghcr.io/yuexps/2fmusic:latest
    container_name: 2fmusic
    ports:
      - "23237:23237"
    volumes:
      - ./:/app/data
    environment:
      - FLASK_ENV=production
      - TZ=Asia/Shanghai
      - PORT=23237
      - APP_PASSWORD=
    restart: unless-stopped