services:
  2fmusic:
    image: ghcr.io/yuexps/2FMusic:latest
    container_name: 2fmusic
    ports:
      - "23237:23237"
    volumes:
      - ./Music:/Music
      - ./app.log:/app.log
    environment:
      - FLASK_ENV=production
      - TZ=Asia/Shanghai
      - PORT=23237
      - APP_PASSWORD=
    restart: unless-stopped
