services:
  2fmusic:
    image: ghcr.io/yuexps/2FMusic:latest
    container_name: 2fmusic
    ports:
      - "23237:23237"
    volumes:
      - ./Music:/app/Music
      - ./app.log:/app/app.log
    environment:
      - FLASK_ENV=production
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8
      - LC_ALL=zh_CN.UTF-8
      - PORT=23237
      - APP_PASSWORD=
    restart: unless-stopped